#!/usr/bin/env python3
"""Export locked gate npzs into src/focusstack/gates.py as literals."""
import numpy as np

def fmt(a):
    return "np.array(" + np.array2string(np.asarray(a, np.float64), separator=", ",
                                         max_line_width=88, precision=8).replace("\n", "\n        ") + ", np.float32)"

veil = dict(np.load("research/t2_gate.npz"))
recon = dict(np.load("research/thinocc_gate.npz"))
body = f'''"""Locked specialist gates (generated by research/export_gates.py — do not edit).

Each gate: ridge weights over the quadratic feature expansion, feature
standardization (mu/sd), and the property-driven fire margin (F47). A candidate
fires when predict_gain(gate, feats) >= gate["margin"].
"""

from __future__ import annotations

import numpy as np

VEIL_GATE = {{
    "w": {fmt(veil["w"])},
    "mu": {fmt(veil["mu"])},
    "sd": {fmt(veil["sd"])},
    "margin": {float(veil["margin"])!r},
}}

RECON_GATE = {{
    "w": {fmt(recon["w"])},
    "mu": {fmt(recon["mu"])},
    "sd": {fmt(recon["sd"])},
    "margin": {float(recon["margin"])!r},
}}


def expand(x: np.ndarray) -> np.ndarray:
    """Quadratic feature map: x plus all pairwise products (order matches training)."""
    q = [x[a] * x[b] for a in range(len(x)) for b in range(a, len(x))]
    return np.concatenate([x, q]).astype(np.float32)


def predict_gain(gate: dict, feats: np.ndarray) -> float:
    """Predicted global-quality gain of firing this candidate."""
    xn = np.hstack([(expand(feats) - gate["mu"]) / gate["sd"], [1.0]])
    return float(xn @ gate["w"])
'''
open("src/focusstack/gates.py", "w").write(body)
# self-check: package predictions reproduce npz math on random vectors
import importlib.util, sys
spec = importlib.util.spec_from_file_location("gates", "src/focusstack/gates.py")
g = importlib.util.module_from_spec(spec); spec.loader.exec_module(g)
rng = np.random.default_rng(0)
for gate_np, gate_py, nf in ((veil, g.VEIL_GATE, 7), (recon, g.RECON_GATE, 7)):
    for _ in range(3):
        x = rng.random(nf).astype(np.float32)
        q = [x[a]*x[b] for a in range(nf) for b in range(a, nf)]
        xe = np.concatenate([x, q]).astype(np.float32)
        ref = float(np.hstack([(xe - gate_np["mu"]) / gate_np["sd"], [1.0]]) @ gate_np["w"])
        got = g.predict_gain(gate_py, x)
        assert abs(ref - got) < 1e-5, (ref, got)
print("gates.py written; predictions match npz")
