#!/usr/bin/env python3
"""M3 — learn a content-features -> best-tune mapping (numpy, no sklearn).

Train a small MLP on the GT-supervised per-tile labels (dev supervision), then
DEPLOY it feature-only (no GT) to route tunes per region on held-out scenes and
blend the per-tune fusions seamlessly (multiband). Success = learned routing
beats the best single global tune and approaches the per-tile oracle.

Run:  python research/learn.py
"""
from __future__ import annotations
import os
import sys

import cv2
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import metrics as M  # noqa: E402
from metrics import _ssim_map, _gray32  # noqa: E402
from focusstack.fusion import fuse_blend, multiband_blend  # noqa: E402
from buildset import make_scene, features, TUNES, RES  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
TILE = 96
N_SCENES = 40
N_TEST = 8


def train_mlp(X, y, nh=48, epochs=800, lr=0.3, l2=1e-4, seed=0):
    rng = np.random.default_rng(seed)
    n, d = X.shape
    k = int(y.max() + 1)
    W1 = rng.normal(0, 0.1, (d, nh)); b1 = np.zeros(nh)
    W2 = rng.normal(0, 0.1, (nh, k)); b2 = np.zeros(k)
    Y = np.eye(k)[y]
    for _ in range(epochs):
        Z1 = X @ W1 + b1; A1 = np.maximum(Z1, 0); Z2 = A1 @ W2 + b2
        Z2 -= Z2.max(1, keepdims=True); P = np.exp(Z2); P /= P.sum(1, keepdims=True)
        dZ2 = (P - Y) / n
        dW2 = A1.T @ dZ2 + l2 * W2; db2 = dZ2.sum(0)
        dZ1 = (dZ2 @ W2.T) * (Z1 > 0)
        dW1 = X.T @ dZ1 + l2 * W1; db1 = dZ1.sum(0)
        W1 -= lr * dW1; b1 -= lr * db1; W2 -= lr * dW2; b2 -= lr * db2
    return (W1, b1, W2, b2)


def predict(model, X):
    W1, b1, W2, b2 = model
    return (np.maximum(X @ W1 + b1, 0) @ W2 + b2).argmax(1)


def route_and_fuse(model, mu, sd, frames, pred=None):
    X = (features(frames, TILE) - mu) / sd
    pred = predict(model, X) if pred is None else pred
    n = RES // TILE
    grid = pred.reshape(n, n)
    W = []
    for t in range(len(TUNES)):
        ind = (grid == t).astype(np.float32)
        full = cv2.resize(ind, (RES, RES), interpolation=cv2.INTER_LINEAR)
        W.append(cv2.GaussianBlur(full, (0, 0), TILE / 2.0))
    W = np.stack(W, 0); W = W / (W.sum(0, keepdims=True) + 1e-8)
    fused = [fuse_blend(frames, **t) for t in TUNES]
    return multiband_blend(fused, W), fused


def main():
    d = np.load(os.path.join(HERE, "trainset.npz"), allow_pickle=True)
    X, y_gt = d["X"], d["y_gt"]
    tiles_per = (RES // TILE) ** 2
    n_train_scenes = N_SCENES - N_TEST
    ntr = n_train_scenes * tiles_per
    Xtr, ytr, Xte, yte = X[:ntr], y_gt[:ntr], X[ntr:], y_gt[ntr:]
    mu, sd = Xtr.mean(0), Xtr.std(0) + 1e-6
    model = train_mlp((Xtr - mu) / sd, ytr)

    acc = (predict(model, (Xte - mu) / sd) == yte).mean()
    base_acc = np.bincount(ytr).argmax()
    base_acc = (yte == base_acc).mean()
    print(f"tile classification: learned acc={acc:.3f}  vs majority-class={base_acc:.3f}")

    # Fusion eval on held-out scenes (regenerated by seed).
    print(f"\nheld-out scene GT-SSIM (routed vs single-tune vs oracle):")
    agg = {f"tune{t}": [] for t in range(len(TUNES))}
    agg.update({"routed": [], "oracle": [], "best_single": [], "content_aware": []})
    for s in range(n_train_scenes, N_SCENES):
        frames, gt = make_scene(s)
        routed, fused = route_and_fuse(model, mu, sd, frames)
        # oracle per-tile (true best by GT)
        ssim = [_ssim_map(_gray32(f), _gray32(gt)) for f in fused]
        n = RES // TILE
        orc = np.zeros(n * n, np.int64)
        for ti in range(n):
            for tj in range(n):
                sl = (slice(ti * TILE, (ti + 1) * TILE), slice(tj * TILE, (tj + 1) * TILE))
                orc[ti * n + tj] = int(np.argmax([sm[sl].mean() for sm in ssim]))
        oracle, _ = route_and_fuse(model, mu, sd, frames, pred=orc)
        ca = fuse_blend(frames, focus_method="content_aware")
        singles = [M.ref_ssim(f, gt) for f in fused]
        for t in range(len(TUNES)):
            agg[f"tune{t}"].append(singles[t])
        agg["best_single"].append(max(singles))
        agg["routed"].append(M.ref_ssim(routed, gt))
        agg["oracle"].append(M.ref_ssim(oracle, gt))
        agg["content_aware"].append(M.ref_ssim(ca, gt))

    def m(k):
        return float(np.mean(agg[k]))
    for t in range(len(TUNES)):
        print(f"  single tune{t} ({TUNES[t]['focus_method']:13s}) {m('tune'+str(t)):.4f}")
    print(f"  --")
    print(f"  best single (per-scene oracle over tunes) {m('best_single'):.4f}")
    print(f"  content_aware operator                    {m('content_aware'):.4f}")
    print(f"  LEARNED per-tile routing                  {m('routed'):.4f}")
    print(f"  per-tile ORACLE routing (upper bound)     {m('oracle'):.4f}")


if __name__ == "__main__":
    main()
